
## CreateUser
POST http://localhost:8080/user HTTP/1.1
content-type: application/json

{
  "name": "John Doe",
  "email": "john.doe2@email.com",
  "password": "12345678@"
}
###

## UpdateUser
PATCH http://localhost:8080/user/9d47a06e-9677-460c-84e3-1bb7ac20b931 HTTP/1.1
  content-type: application/json

{
  "name": "John Doe",
  "email": "john.doe2s@email.com",
  "cep": "88132243"
}
###

 ## GetUserByID
  GET http://localhost:8080/user/9d47a06e-9677-460c-84e3-1bb7ac20b931 HTTP/1.1
  content-type: application/json
  
  ####